image: Visual Studio 2022

environment:
  TIB: true

configuration: Release
platform: x64

install:
  - nuget restore packages.config -PackagesDirectory packages\

# Disable the default build phase to avoid "multiple solution files" error
build: off

before_build:
  - cmd: build\build_init.cmd

build_script:
  # Pass < nul to bypass 'pause' commands in the scripts
  - cmd: build\build_release.cmd < nul

artifacts:
  - path: bin\**\*.exe
  - path: bin\**\*.sys
  - path: bin\**\*.dll

deploy: off
